# Generated by Django 4.2.7 on 2023-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messages_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="last_message_id",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("contact_id", "message_id")},
        ),
    ]
