# Generated by Django 4.2.6 on 2023-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffile",
            name="company_name",
            field=models.CharField(default="NOME DA EMPRESA", max_length=255),
        ),
    ]
