# Generated by Django 4.2.6 on 2023-11-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0002_pdffile_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdffile",
            name="grouping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdfs",
                to="control.dasfilegrouping",
            ),
        ),
    ]
