# Generated by Django 4.2.6 on 2023-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0002_dasfilegrouping_was_sent_messagecontrol_check_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messagecontrol",
            old_name="contact",
            new_name="contact_number",
        ),
        migrations.AddField(
            model_name="messagecontrol",
            name="digisac_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
