# Generated by Django 4.2.6 on 2023-11-10 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0003_alter_pdffile_grouping"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdffile",
            old_name="pdf",
            new_name="file",
        ),
    ]
